FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    libxml2-dev \
    libjpeg-dev \
    libpng-dev \
    libxslt1-dev \
    git \
    curl \
    wget \
    libatlas-base-dev \
    libgl1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

COPY backend/requirements-heavy.txt .
RUN pip install --no-cache-dir -r requirements-heavy.txt

